import {StyleSheet} from 'react-native';

export default Exstyles = StyleSheet.create({
  textBox: {
    color: '#F4EEEE',
    fontSize: 35,
    padding: 10,
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 1,
  },
  text: {
    color: '#F4EEEE',
    fontSize: 30,
    padding: 10,
    margin: 10,
    borderRadius: 1,
    borderColor: 'white',
    borderWidth: 0.2,
  },
  textInput: {
    color: '#fff',
    fontSize: 20,
    margin: 5,
    padding: 5,
    borderRadius: 5,
    borderColor: 'white',
    borderWidth: 0.5,
  },
  list: {
    color: '#fff',
    fontSize: 15,
    margin: 5,
    padding: 5,
    borderRadius: 5,
    borderColor: 'white',
    borderWidth: 0.5,
  },
  viewBox: {
    padding: 15,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 5,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 25,
    marginBottom: 10,
  },
  grid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  items: {
    borderColor: 'greenyellow',
    fontSize: 25,
    borderWidth: 0.5,
    height: 110,
    width: 110,
    margin: 5,
    padding: 5,
    textAlignVertical: 'center',
    textAlign: 'center',
    borderRadius: 15,
  },
});
